version: "3.8"

services:
    flask:
        build:
            dockerfile: ./Dockerfile
            context: .
        container_name: inf5190.tp1
        volumes:
            - ./:/app
        ports:
          - 5000:5000
        environment:
          - FLASK_ENV=development
